package com.eainde.prompt.quality.fix;

/**
 * An actionable fix suggestion for a detected prompt quality issue.
 *
 * <p>Generated by analyzers implementing {@link FixGenerator} and applied
 * via {@link PromptFixApplicator}.</p>
 *
 * @param ruleId      the rule that triggered this fix (e.g., "CLR-001")
 * @param description human-readable summary of the fix
 * @param fixType     INSERT, REPLACE, or DELETE
 * @param location    where to apply: SYSTEM_PROMPT or USER_PROMPT
 * @param anchor      text to locate the insertion/replacement point (null = prepend)
 * @param replacement the text to insert or replace with
 * @param confidence  HIGH/MEDIUM/LOW — how safe it is to auto-apply
 */
public record PromptFix(
        String ruleId,
        String description,
        FixType fixType,
        FixLocation location,
        String anchor,
        String replacement,
        FixConfidence confidence
) {}
